-- LIMPIAR TABLAS:

TRUNCATE TABLE 
    log_auditoria, 
    nomina_empleados, 
    cuentas_por_cobrar, 
    cortes_caja, 
    gastos_sucursal 
RESTART IDENTITY CASCADE;

--DDL:

CREATE TABLE public.cuentas_por_cobrar (
	id_cuenta int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	id_cliente_ref int4 NULL,
	monto_deuda varchar NULL,
	fecha_limite date NULL,
	estado_pago varchar NULL,
	CONSTRAINT cuentas_por_cobrar_pk PRIMARY KEY (id_cuenta)
);

CREATE TABLE public.cortes_caja (
	id_corte int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	fecha_corte date NULL,
	ingresos_totales varchar NULL,
	egresos_totales varchar NULL,
	saldo_final varchar NULL,
	CONSTRAINT cortes_caja_pk PRIMARY KEY (id_corte)
);

CREATE TABLE public.gastos_sucursal (
	id_gasto int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	concepto varchar NULL,
	monto varchar NULL,
	fecha_gasto date NULL,
	CONSTRAINT gastos_sucursal_pk PRIMARY KEY (id_gasto)
);

CREATE TABLE public.log_auditoria (
	id_log int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	usuario varchar NULL,
	modulo varchar NULL,
	accion varchar NULL,
	fecha date NULL,
	detalles varchar NULL,
	CONSTRAINT log_auditoria_pk PRIMARY KEY (id_log)
);

CREATE TABLE public.nomina_empleados (
	id_nomina int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	rfc_empleado varchar NULL,
	sueldo_pagado varchar NULL,
	fecha_pago date NULL,
	bonos varchar NULL,
	CONSTRAINT nomina_empleados_pk PRIMARY KEY (id_nomina)
);

--========================================================================40 consultas=================================================================================================

-- 81. Mostrar todos los cortes de caja
SELECT * FROM public.cortes_caja;

-- 82. Mostrar todos los gastos de sucursal registrados
SELECT * FROM public.gastos_sucursal;

-- 83. Mostrar todas las cuentas por cobrar
SELECT * FROM public.cuentas_por_cobrar;

-- 84. Mostrar toda la nómina pagada
SELECT * FROM public.nomina_empleados;

-- 85. Sumar todo el dinero ingresado en los cortes de caja
SELECT SUM(ingresos_totales::NUMERIC) AS total_dinero_ingresado 
FROM public.cortes_caja;

-- 86. Calcular el sueldo promedio de los empleados
SELECT AVG(sueldo_pagado::NUMERIC) AS sueldo_promedio 
FROM public.nomina_empleados;

-- 87. Mostrar el gasto de sucursal más caro
SELECT * FROM public.gastos_sucursal 
ORDER BY monto::NUMERIC DESC 
LIMIT 1;

-- 88. Contar cuántos registros hay en el log de auditoría
SELECT COUNT(*) AS total_registros_auditoria 
FROM public.log_auditoria;

-- 89. Contar cuántas nóminas se le han pagado a cada RFC de empleado
SELECT 
    rfc_empleado, 
    COUNT(*) AS total_nominas_pagadas 
FROM public.nomina_empleados 
GROUP BY rfc_empleado;

-- 90. Sumar la deuda total pendiente en cuentas_por_cobrar
SELECT SUM(monto_deuda::NUMERIC) AS deuda_total_pendiente 
FROM public.cuentas_por_cobrar 
WHERE estado_pago = 'Pendiente';

-- 91. Mostrar logs donde la acción sea 'DELETE'
SELECT * FROM public.log_auditoria 
WHERE accion = 'DELETE';

-- 92. Extraer y mostrar el valor de la llave 'ip_responsable' del JSON en los logs

SELECT 
    id_log,
    usuario,
    detalles::json->>'ip_responsable' AS ip_responsable
FROM public.log_auditoria;

-- 93. Mostrar los cortes de caja generados el día de hoy
SELECT * FROM public.cortes_caja 
WHERE fecha_corte = CURRENT_DATE;

-- 94. Mostrar cuentas por cobrar con estado 'Atrasado'
SELECT * FROM public.cuentas_por_cobrar 
WHERE estado_pago = 'Atrasado';

-- 95. Mostrar gastos por concepto de 'Luz' o 'Agua'
SELECT * FROM public.gastos_sucursal 
WHERE concepto IN ('Luz', 'Agua');

-- 96. Mostrar los distintos conceptos de gastos registrados (sin repetir)
SELECT DISTINCT concepto 
FROM public.gastos_sucursal;

-- 97. Mostrar las 3 nóminas más altas pagadas (LIMIT)
SELECT * FROM public.nomina_empleados 
ORDER BY sueldo_pagado::NUMERIC DESC 
LIMIT 3;

-- 98. Agrupar por fecha y contar cuántos gastos se registraron ese día
SELECT 
    fecha_gasto, 
    COUNT(*) AS cantidad_gastos 
FROM public.gastos_sucursal 
GROUP BY fecha_gasto;

-- 99. Mostrar gastos cuyo monto esté entre $1,000 y $5,000
SELECT * FROM public.gastos_sucursal 
WHERE monto::NUMERIC BETWEEN 1000 AND 5000;

-- 100. Mostrar IDs de clientes que deben más de $10,000
SELECT id_cliente_ref, monto_deuda 
FROM public.cuentas_por_cobrar 
WHERE monto_deuda::NUMERIC > 10000;

-- 101. Mostrar logs donde el módulo sea 'Punto de Venta'
SELECT * FROM public.log_auditoria 
WHERE modulo = 'Punto de Venta';

-- 102. Calcular el saldo final promedio de los cortes de caja
SELECT AVG(saldo_final::NUMERIC) AS saldo_final_promedio 
FROM public.cortes_caja;

-- 103. Mostrar los conceptos de gastos en MAYÚSCULAS
SELECT UPPER(concepto) AS concepto_mayusculas 
FROM public.gastos_sucursal;

-- 104. Mostrar cuentas por cobrar ordenadas por fecha límite de más próxima a más lejana
SELECT * FROM public.cuentas_por_cobrar 
ORDER BY fecha_limite ASC;

-- 105. Mostrar el monto de la deuda con un interés del 5% simulado por mora
SELECT 
    id_cuenta,
    monto_deuda AS deuda_original,
    (monto_deuda::NUMERIC * 1.05) AS deuda_con_interes_5porciento
FROM public.cuentas_por_cobrar;

-- 106. Mostrar cuentas por cobrar con estado 'Pagado'
SELECT * FROM public.cuentas_por_cobrar 
WHERE estado_pago = 'Pagado';

-- 107. Mostrar nóminas que incluyeron algún bono (bonos > 0)
SELECT * FROM public.nomina_empleados 
WHERE bonos::NUMERIC > 0;

-- 108. Contar cuántos logs hay agrupados por módulo
SELECT 
    modulo, 
    COUNT(*) AS total_logs 
FROM public.log_auditoria 
GROUP BY modulo;

-- 109. Mostrar el corte de caja del día en que se registró el gasto más fuerte (Subconsulta)
SELECT * FROM public.cortes_caja 
WHERE fecha_corte = (
    SELECT fecha_gasto 
    FROM public.gastos_sucursal 
    ORDER BY monto::NUMERIC DESC 
    LIMIT 1
);

-- 110. Mostrar nóminas que superen el sueldo promedio general (Subconsulta)
SELECT * FROM public.nomina_empleados 
WHERE sueldo_pagado::NUMERIC > (
    SELECT AVG(sueldo_pagado::NUMERIC) 
    FROM public.nomina_empleados
);

-- 111. Mostrar la longitud de caracteres del campo JSON en la tabla de logs
SELECT 
    id_log,
    detalles,
    LENGTH(detalles) AS longitud_caracteres_json
FROM public.log_auditoria;


-- 112. Mostrar el pago de nómina más bajo en el historial
SELECT * FROM public.nomina_empleados 
ORDER BY sueldo_pagado::NUMERIC ASC 
LIMIT 1;

-- 113. Mostrar cuentas por cobrar cuyo monto supere el promedio de deudas
SELECT * FROM public.cuentas_por_cobrar 
WHERE monto_deuda::NUMERIC > (
    SELECT AVG(monto_deuda::NUMERIC) 
    FROM public.cuentas_por_cobrar
);

-- 114. Mostrar los 10 logs de auditoría más recientes ordenados por fecha
SELECT * FROM public.log_auditoria 
ORDER BY fecha DESC 
LIMIT 10;

-- 115. Sumar el monto de gastos operativos agrupado por concepto
SELECT 
    concepto, 
    SUM(monto::NUMERIC) AS total_gasto 
FROM public.gastos_sucursal 
GROUP BY concepto;

-- 116. Mostrar el ID del cliente con la deuda más alta activa
SELECT id_cliente_ref 
FROM public.cuentas_por_cobrar 
WHERE estado_pago = 'Pendiente' 
ORDER BY monto_deuda::NUMERIC DESC 
LIMIT 1;

-- 117. Contar cuántos empleados distintos (RFCs) están en la nómina
SELECT COUNT(DISTINCT rfc_empleado) AS total_empleados_distintos 
FROM public.nomina_empleados;

-- 118. Mostrar registros de logs del mes actual (usando EXTRACT)
SELECT * FROM public.log_auditoria 
WHERE EXTRACT(MONTH FROM fecha) = EXTRACT(MONTH FROM CURRENT_DATE)
  AND EXTRACT(YEAR FROM fecha) = EXTRACT(YEAR FROM CURRENT_DATE);

-- 119. Agrupar nóminas por mes y mostrar la suma total pagada
SELECT 
    EXTRACT(MONTH FROM fecha_pago) AS mes_pago, 
    SUM(sueldo_pagado::NUMERIC) AS total_pagado 
FROM public.nomina_empleados 
GROUP BY EXTRACT(MONTH FROM fecha_pago)
ORDER BY mes_pago ASC;

-- 120. Mostrar logs donde el JSON tenga un nivel de error crítico
SELECT * FROM public.log_auditoria 
WHERE detalles::json->>'nivel' = 'critico';


--=============================================================================TRIGGERS==================================================================================================

--15. Bloquear UPDATE y DELETE en cortes_caja

CREATE OR REPLACE FUNCTION FN_Cortes_Inmutables()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'La tabla cortes_caja es inmutable por política fiscal';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_Cortes_Inmutables_Update
BEFORE UPDATE ON cortes_caja
FOR EACH ROW
EXECUTE FUNCTION FN_Cortes_Inmutables();

CREATE TRIGGER TRG_Cortes_Inmutables_Delete
BEFORE DELETE ON cortes_caja
FOR EACH ROW
EXECUTE FUNCTION FN_Cortes_Inmutables();


--16. Validar que exista la llave usuario_sistema

CREATE OR REPLACE FUNCTION FN_Valida_JSON_Auditoria()
RETURNS TRIGGER AS $$
BEGIN
    IF NOT (NEW.detalles::jsonb ? 'usuario_sistema') THEN
        RAISE EXCEPTION 
        'El JSON de auditoría debe contener la llave usuario_sistema';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_Valida_JSON_Auditoria
BEFORE INSERT ON log_auditoria
FOR EACH ROW
EXECUTE FUNCTION FN_Valida_JSON_Auditoria();


--17. Validar sueldo mínimo

CREATE OR REPLACE FUNCTION FN_Sueldo_Justo()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.sueldo_pagado < 7500 THEN
        RAISE EXCEPTION 
        'Error: sueldo menor al salario mínimo permitido';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_Sueldo_Justo
BEFORE INSERT ON nomina_empleados
FOR EACH ROW
EXECUTE FUNCTION FN_Sueldo_Justo();


--18. Mandar NOTICE si deuda > 50000

CREATE OR REPLACE FUNCTION FN_Aviso_Deuda_Grande()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.monto_deuda > 50000 THEN
        RAISE NOTICE 
        'Aprobación de Crédito Especial Requerida';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_Aviso_Deuda_Grande
BEFORE INSERT ON cuentas_por_cobrar
FOR EACH ROW
EXECUTE FUNCTION FN_Aviso_Deuda_Grande();


--19. Bloquear deudas negativas

CREATE OR REPLACE FUNCTION FN_Deuda_Negativa()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.monto_deuda < 0 THEN
        RAISE EXCEPTION 
        'Error: no se permiten montos negativos en cuentas por cobrar';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_Deuda_Negativa
BEFORE INSERT ON cuentas_por_cobrar
FOR EACH ROW
EXECUTE FUNCTION FN_Deuda_Negativa();


--20. Bloquear DELETE en log_auditoria

CREATE OR REPLACE FUNCTION FN_Auditoria_Intocable()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 
    'Los registros de auditoría de finanzas son inmutables por ley';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_Auditoria_Intocable
BEFORE DELETE ON log_auditoria
FOR EACH ROW
EXECUTE FUNCTION FN_Auditoria_Intocable();